
modLoader="javafml" #mandatory
license= "All Rights Reserved"
loaderVersion="${loader_version_range}" #mandatory

[[mods]]
version="${mod_version}"
description='''
Turn your world into Warrior Cats!
'''
authors="Klyonstar / Snowstar"
credits=""
logoFile= "../../resources/banner.png"
logoBlur = false
updateJSONURL=""
displayURL="https://modrinth.com/mod/warrior-cats-events"
modId="${mod_id}"
displayName="${mod_name}"

[[mixins]]
config = "mixins.warriorcats_events.json"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="geckolib"
    type="required"
    versionRange="[4.8.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="walkers"
    type="required"
    versionRange="[5.8.7,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="craftedcore"
    type="required"
    versionRange="[5.8,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="patchouli"
    type="required"
    versionRange="[1.20.1-84,)"
    ordering="NONE"
    side="BOTH"







